### ISSUE TITLE
Incorrect chart display

### ISSUE THREAD

**Issue by BigCosta** [sghaskell/custom-radar-chart-viz#4]
If there are several keys, and there is no axis in one key, the diagram displays the values for this key on the wrong axes.
Example: 
Table for chart:
**key | axis | value**
root | China | 1362
root | Chile | 749
root | United States | 549
admin | Germany | 811
admin | Romania | 637

Chart for admin key is not displayed correctly 
![radar_bug](https://user-images.githubusercontent.com/23712475/60736569-a1766800-9f81-11e9-989f-e47148ea2539.PNG)

**Comment by sghaskell** [comment]
Thanks @BigCosta for reporting this. I'll have a look and see what I can do about fixing it or suggesting a workaround.

**Comment by sghaskell** [comment]
@BigCosta I just released version 1.0.6 on Splunkbase that should fix the glitch.

<img width="1645" alt="Screen Shot 2019-07-11 at 3 26 04 PM" src="https://user-images.githubusercontent.com/8450537/61089543-4e246f80-a3f0-11e9-917b-b9f7350fa7ac.png">

**Comment by sghaskell** [comment]
Fixed by [abd537e](https://github.com/sghaskell/custom-radar-chart-viz/commit/abd537e29895cb5161065d159617c6a2f0302e4a)

**Comment by BigCosta** [comment]
Hi sghaskell!
I tested version 1.0.6 and find what bug not completely fixed. I found new composition with error.

**Initial data**
key,axis,value
admin,China,20
admin,United States,10
root,China,30
root,Germany,35
root,United States,5
test,China,40
test,United States,15

Chart for admin and test keys is not displayed correctly

![radar_bug_2](https://user-images.githubusercontent.com/23712475/61180164-5375fa00-a63c-11e9-88f3-2533a91278b0.PNG)

**Comment by sghaskell** [comment]
Thanks @BigCosta . I'll take another look.

**Comment by sghaskell** [comment]
Seems to work fine for me. Have you tried clearing your browser cache and re-running?

<img width="1643" alt="Screen Shot 2019-07-15 at 9 58 55 AM" src="https://user-images.githubusercontent.com/8450537/61234141-334f4500-a6e7-11e9-867b-7869793ab4ec.png">

**Comment by BigCosta** [comment]
Yes, I cleared browser cache. And your example works fine, but there is a difference in the source data.
The problem occurs when the first key has an incomplete axis set.
Add sort command at end for put the admin key in the first place for getting original test data.
`| sort key`

p.s. After adding the sort command and starting the search, I had to additionally manually refresh the browser page to redraw the chart with new data. Perhaps this is also a bug.

**Comment by sghaskell** [comment]
Thanks @BigCosta for the detailed explanation. It looks like it's because I'm not sorting the axes. I'll update, test and push out a new release shortly. I'll also try to sneak in some fixes for the other issues you're seeing.

**Comment by sghaskell** [comment]
@BigCosta - Try version 1.1.0 . This and many other issues have been addressed.

**Comment by sghaskell** [comment]
[Fixed by a580128](https://github.com/sghaskell/custom-radar-chart-viz/blob/master/appserver/static/visualizations/radar_chart/src/radar_chart.js#L77-L79)
